export const SEARCH_SONGS           = 'SEARCH_SONGS'
export const SEARCHING_SONGS        = 'SEARCHING_SONGS'
export const SEARCH_SONGS_FAILED    = 'SEARCH_SONGS_FAILED'
export const SEARCH_SONGS_SUCCEEDED = 'SEARCH_SONGS_SUCCEEDED'
